Fix missing underscore
Will resolve the issue below

Logger: homeassistant.components.sensor
Source: custom_components/solarman/solarman.py:34
Integration: Sensor (documentation, issues)
First occurred: 19:54:15 (1 occurrences)
Last logged: 19:54:15

Error while setting up solarman platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/solarman/sensor.py", line 79, in async_setup_entry
    _do_setup_platform(hass, entry.options, async_add_entities)
  File "/config/custom_components/solarman/sensor.py", line 51, in _do_setup_platform
    inverter = Inverter(path, inverter_sn, inverter_host, inverter_port, inverter_mb_slaveid, lookup_file)
  File "/config/custom_components/solarman/solarman.py", line 34, in __init__
    with open(self.path + lookup_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/config/custom_components/solarman/inverter_definitions/sofar wifikit.yaml'